738<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月17日(金) 11:55<>ひで<>部品の結合<>お世話になります<br><br>アセンブリではなく部品同士をつなげて<br>ひとつの部品(ipt)にすることは可能でしょうか<br>もし可能でしたら作業方法を教えていただけないでしょうか<br>よろしくお願いします<>#c7c7a8<>1WEHqx8.w2kMo<>softbank126113000210.biz.bbtec.net<>
739<>738<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月17日(金) 12:40<>管理人<><>お世話様です。<br><br>バージョン2014ならアセンブリの簡略化で簡略化パーツを作成すればひとつのパーツになりますが、それではダメでしょうか。<>#c7c7a8<><>pc6adc7.miygnt01.ap.so-net.ne.jp<>
740<>738<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月17日(金) 13:22<>ひで<><>なるほど！<br>うまいことできました<br>ありがとうございます<>#c7c7a8<>TQURc.cx5qO8c<>softbank126113000210.biz.bbtec.net<>
728<><>png!:150!:124!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月12日(日) 10:23<>INVENTORING<>右クリックのカスタマイズ<>いつもお世話になります。<br>ブラウザでパーツ選択状態の右クリックのメニューはカスタマイズできるでしょうか？<br>具体的には新規フォルダに追加(A)とアダプティブ(A)が同じAボタンのため、現在はアダプティブを選択するのにAボタンを二回押しエンターを押しているのですが、非常に使い勝手が悪いです。ショートカットキーのように自分でカスタマイズできればと思い質問させていただきました。<br>よろしく願いいたします<>#b8a8c7<>vJ2U1KG8lSoms<>237.88.223.223.megaegg.ne.jp<>
729<>728<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月14日(火) 10:34<>管理人<><>お世話様です。<br><br>Autodeskに問い合わせてみましたが、ブラウザの右クリックのカスタマイズはないそうです。<br><br>残念ながら次のバージョンに期待するしかないようですね。<>#c7c7a8<><>pc6adc7.miygnt01.ap.so-net.ne.jp<>
743<>728<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月19日(日) 13:01<>INVENTORING<><>返事が遅れてすみません。<br>わざわざありがとうございました！<br>作業性向上のために何かほかの案を考えてみます。<br><>#b8a8c7<>j3E88NPA6oLTA<>237.88.223.223.megaegg.ne.jp<>
744<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月20日(月) 15:51<>ひで<>モデルのスケール変更<>お世話になります<br><br>表題なのですが<br>一度作成したモデルを全体的にスケール変更したい場合<br>単純な絵でしたら作り直せばいいのですが<br>複雑というか再描画がめんどくさい場合、変更できれば。。と思ったのですが何かいい方法はありますでしょうか<br><>#c7c7a8<>DgVb/mZOaJTVs<>softbank126113000210.biz.bbtec.net<>
746<>744<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月20日(月) 17:44<>お世話様です。<><>図面の尺度ではないですよね。<br>アセンブリの尺度？を全体的に変更するということでしょうか？<>#c7c7a8<><>pc6adc7.miygnt01.ap.so-net.ne.jp<>
747<>744<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月20日(月) 18:48<>ひで<><>図面でもアセンブリでもなく<br>個々のパーツ（部品ipt）自体の尺度（サイズ）変更がしたいのです<br><br>例えるなら10cm角の立方体を作画したとして<br>その後その絵自体を5cm角の立方体にサイズ変更したい<br>※この場合だと全体的に1/2の縮尺<br>的な感じです<br>一部変更ではなく、全体的に尺度を変えたく<br>書き直しがめんどくさい（形状が複雑な）場合、<br>一発で変えられないものかなと思いまして。。<>#c7c7a8<>tTrpR14FR/DFM<>softbank126113000210.biz.bbtec.net<>
748<>744<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月20日(月) 19:57<>管理人<><>失礼しました。<br><br>管理のパーツを作成で尺度を変更すると出来るようです。<br>フィーチャやスケッチをそのままコピーは出来ない？ような感じですが、お試しください。<>#c7c7a8<>QXiFtN6ElaV1g<>pc6adc7.miygnt01.ap.so-net.ne.jp<>
749<>744<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月21日(火) 14:46<>jp.cadmama<><>派生すると「尺度」を変更した派生パーツを作成できます。<br>管理の「パーツを作成」コマンドも、派生の機能を使用しています。<br><br>ただ、派生でよいのか…後々のことも良く考えて使用したほうが良いと思います。<br>パラメータが無くなるので、修正は困難なものになります。<>#c7c7a8<>JS02l2Wa9Ru3.<>202.238.175.90<>
751<>744<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月21日(火) 14:57<>ひで<><>なるほど。<br>確かに尺度は変更できましたが<br>一つの塊としてしまうようですね<br>単純に一筋縄ではいかないようなのですね<br><br>ありがとうございました<>#c7c7a8<>qHe43fgwPF6/I<>softbank126113000210.biz.bbtec.net<>
753<>744<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月21日(火) 17:17<>jp.cadmama<><>パーツを「名前を付けて保存」して別パーツを作成し「管理タブ＞パラメータ」の値を想定している尺度分を係数として、かけた値に変更してみてはいかがでしょうか？<>#c7c7a8<>Kh5O6fwdoHcmc<>202.238.175.90<>
754<>744<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月21日(火) 18:10<>ひで<><>別の手法の提案ありがとうございます<br>早速試しにすべての数値を半分にした値で入力してみましたが<br>やり方の問題なのかもしれませんが<br>フィレット等でエラーが出てしまうようです<br><br>…難しいですね（汗<>#c7c7a8<>XiYZrrAtfQ0m2<>softbank126113000210.biz.bbtec.net<>
742<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月18日(土) 16:00<>ゼネバ機構<>ポム<>ゼネバ機構の拘束で悩んでいます<br>歯車同士の拘束モーションまでは行けたのですが<br>そこにゼネバ機構が噛んでいるのでそいつのシミュレート出来ないでいます<br>よろしくお願いいたします<>#c7c7a8<>Bx6yokbSVjDP6<>p6025-ipbfp404oomichi.oita.ocn.ne.jp<>
745<>742<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月20日(月) 17:38<>管理人<><>お世話様です。<br><br>環境のダイナミックシミュレーションでジョイント挿入の3D接触で出来るはずなのですが、うまくいきませんでした。<br>Autodeskに問い合わせましたが、同様にきちんと動作しないようです。<br>エンジニアに問い合わせるようなので今しばらくお待ちください。<>#c7c7a8<><>pc6adc7.miygnt01.ap.so-net.ne.jp<>
750<>742<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月21日(火) 14:51<>jp.cadmama<><>ゼネバ機構の拘束駆動は「接触セット」と「接触ソルバ」を使用すると、動作表現できます。<>#c7c7a8<>0FG.XutrC5xL.<>202.238.175.90<>
755<>742<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月22日(水) 15:32<>管理人<><>お世話様です。<br><br>下記にダイナミックシミュレーションのやり方を掲載しましたのでご参考にしてください。<br><br>http://inventorroom.net/con_dynamicsimulation1.html<>#c7c7a8<>7SYKVReOln2R6<>pc6adc7.miygnt01.ap.so-net.ne.jp<>
767<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月25日(土) 17:33<>INVENTORING<>完成しました！！<>ついにできました！<br>費やした時間30時間以上、、、<br>あきらめてほかのプログラムを組んでいるときにたまたま発見しました。<br>長文のため、ご迷惑をおかけしますが、用途が合えば非常に役に立つプログラムだと思いますので、ここに掲載させていただきます。<br>内容は「モデリングしたパーツのXYZ各軸の最大寸法を測定して、ipropertyの説明の部分に入力する」というものです。<br>欠点は各軸に対して斜めにモデリングしてある直方体などは、形状を製作するのに必要な最小寸法より大きな寸法が表示されるということです。<br>以下をilogicにコピペしていただければ使用できると思います。<br>'パーツのXYZの最長距離を測定して格納する<br>Dim oPartDoc As PartDocument<br>oPartDoc = ThisDoc.Document<br>If oPartDoc.ComponentDefinition.SurfaceBodies.Count &gt;1 Then<br>    BBox_X=0<br>    BBox_Y=0<br>    BBox_Z=0<br>	Exit Sub<br>End If<br>Dim oBox As Box<br>Try<br>    oBox = oPartDoc.ComponentDefinition.SurfaceBodies.Item(1).RangeBox<br>Catch<br>    BBox_X=0<br>    BBox_Y=0<br>    BBox_Z=0<br>    Exit Sub<br>End Try<br>     BBox_X= FormatNumber( oBox.MaxPoint.X-oBox.MinPoint.X,5)<br>     BBox_Y= FormatNumber( oBox.MaxPoint.Y-oBox.MinPoint.Y,5)<br>     BBox_Z= FormatNumber( oBox.MaxPoint.Z-oBox.MinPoint.Z,5)<br><br>Parameter.Quiet = True<br>'格納したデータの桁数をそろえる<br>BBox_X=BBox_X*10<br>BBox_Y=BBox_Y*10<br>BBox_Z=BBox_Z*10<br>Dim a As Double<br>Dim b As Double<br>Dim c As Double<br>'格納した寸法を小さい順に並び替えipropertyに出力<br>If BBox_X&gt;=BBox_Y Then<br>	If BBox_Y&gt;=BBox_Z Then<br>	c=BBox_X<br>	b=BBox_Y<br>	a=BBox_Z<br>		Else<br>		If BBox_Z&gt;=BBox_X Then<br>		c=BBox_Z<br>		b=BBox_X<br>		a=BBox_Y<br>		Else<br>		c=BBox_X<br>		b=BBox_Z<br>		a=BBox_Y<br>		End If<br>	End If<br>	Else<br>	If BBox_X&gt;=BBox_Z Then<br>	c=BBox_Y<br>	b=BBox_X<br>	a=BBox_Z<br>		Else<br>		If BBox_Y&gt;=BBox_Z Then<br>		c=BBox_Y<br>		b=BBox_Z<br>		a=BBox_X<br>		Else<br>		c=BBox_Z<br>		b=BBox_Y<br>		a=BBox_X<br>		End If<br>	End If<br>End If<br>'小数点をそろえる<br>a=Round(a, 1)<br>b=Round(b, 1)<br>c=Round(c, 1)<br>'テキスト形式にしてカスタムプロパティに出力（数値のままだと10が10.0という表示になるため<br>iProperties.Value(&quot;Custom&quot;, &quot;a&quot;)=CStr(a)<br>iProperties.Value(&quot;Custom&quot;, &quot;b&quot;)=CStr(b)<br>iProperties.Value(&quot;Custom&quot;, &quot;c&quot;)=CStr(c)<br>iProperties.Value(&quot;Project&quot;, &quot;Description&quot;)=&quot;=&lt;a&gt;x&lt;b&gt;x&lt;c&gt;&quot;<br><br>ご協力してくださった皆様、ありがとうございました。今後もよろしくお願いいたします。<>#b8a8c7<>vlvbvxAQiVFAk<>237.88.223.223.megaegg.ne.jp<>
768<>767<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月25日(土) 19:42<>管理人<><>お世話様です。<br><br>お疲れ様でした。<br>確認しましたが、確かに説明の部分に寸法が入ってました。<br>すばらしい。<br>有効に活用させていただきます。<>#c7c7a8<>0TRi/fxhBY1HY<>pc6adc7.miygnt01.ap.so-net.ne.jp<>
762<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月24日(金)  9:08<>ひで<>文字の反転<>お世話になります<br><br>はんこ的なものを作成したいのですが、<br>文字の反転方法のやり方ご教授願えないでしょうか<br>文字作成→パターン：ミラーでいけると思ってたのですが<br>ミラーコマンド時に文字が選択できませんでした<br>よろしくお願いします<>#c7c7a8<>QaE954HJU9sLU<>softbank126113000210.biz.bbtec.net<>
763<>762<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月24日(金)  9:39<>管理人<><>お世話様です。<br><br>文字自体のミラーは出来ないようですね。<br><br>ペイントなどのソフトで文字を反転した画像を作成してそれをスケッチ→挿入→イメージで挿入してはどうでしょうか。<br><br>あとはアセンブリを作成して文字の部分を厚み0.01ぐらいの透明なパーツにしてそこに文字を作成し、それを本体部分のパーツに反転した状態で拘束すれば見た目ははんこに見えますね。<>#c7c7a8<>b2vqu0JhQD2QA<>pc6adc7.miygnt01.ap.so-net.ne.jp<>
764<>762<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月24日(金)  9:54<>ひで<><>回答ありがとうございます<br><br>スケッチ→挿入→イメージやってみましたが<br>イメージが貼り付けられるだけでそのものを押し出すことはできないのですね<br><br>いろいろ考えてたところ<br>表に書いた文字を単に反対側へ押し出せば<br>文字が反転する事に気づきました<br>お騒がせしました<>#c7c7a8<>TXCJVa32JoNPg<>softbank126113000210.biz.bbtec.net<>
769<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月27日(月)  8:50<>ひで<>文字の押し出し<>お世話になります<br><br>文字の押し出しもしくはエンボスについてなのですが<br>書体により出来ないものがあります<br>---------------<br>   押し出しフィーチャの作成に失敗しました<br>     Part1: 更新中にエラーが発生しました<br>       押し出し2: この 押し出し は作成できませんでした<br>         このプロファイル内に自己交差ループがあります。曲線の交差にスケッチ点を追加するか、非プロファイル ジオメトリを構築ジオメトリに変更して交差を除去してください。<br>---------------<br>明朝体を指定すると出るのですが<br>この書体を用いるとして回避方法ありますでしょうか<br>どこかが交差しているのでそれを除去できればいけるような気はするのですが<br>文字での描画のため(黒く塗りつぶされてる)交差箇所がわかりません・・・<br>よろしくお願いします<>#c7c7a8<>L63.9jB0F7cFw<>softbank126113000210.biz.bbtec.net<>
770<>769<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2014年1月27日(月) 12:51<>管理人<><>お世話様です。<br><br>試してみましたが、明朝体でもＡＲＰ明朝はＮＧでしたがＨＧ明朝はＯＫでした。ＡＲＰ明朝でもＮＧな字とＯＫな字があるようですね。（ＨＧ明朝でも同じことが言えるかもしれません）<br><br>すいませんが、ＮＧの字をＯＫにする方法はわかりませんでした。<br><br><br><>#c7c7a8<><>pc6adc7.miygnt01.ap.so-net.ne.jp<>
