1163<><>jpg!:150!:80!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月11日(水) 10:55<>初心者2号<>色設定<>現在inventor導入を考え、お試し版で練習して<br>１週間のウルトラ初心者です。<br>モデルの色設定ですがAutoCadのように色サンプルがあって<br>そこから色を選べないのでしょうか？<br>またお試し版では色が変更できないようになっているのでしょうか？<br>添付資料のような色変更で操作はあっているのでしょうか？<br>初心者質問で申し訳ありませんが<br>ご教授ください。<br><>#c7c7a8<><>tamarind.aitai.ne.jp<>
1164<>1163<>jpg!:150!:138!:1!:png!:150!:149!:1!:!:!:!:!:!:!:!:!:<>2015年3月11日(水) 11:25<>管理人<><>お世話様です。<br><br>色の設定は外観エディタで出来ますのでお試しください。<br><br>外観エディタは色をダブルクリックで開きますが、既存の色は変更が出来ないようなので新しく外観を作るか、ドキュメント外観にある既定を複製しそれを編集してもいいと思います。<>#c7c7a8<>s8K4GpalyYAYo<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1165<>1163<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月11日(水) 16:36<>初心者2号<>ありがとうございました<>早速のご回答感謝します。<br>前述のとおりウルトラ初心者ですので<br>またお願いしたいと思います。<br>よろしくお願いします。<>#c7c7a8<><>tamarind.aitai.ne.jp<>
1160<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月9日(月) 23:40<>sh<>2Dエクスポートについて<>管理人様<br>いつもお世話になっております。<br><br>inventor2013において、idwからautocad dwgファイルに変換する際にidwのブロック(prt)をブロックのままエクスポートできるでしょうか？<br>線が多くなればなるほど何の線か分からなくなってしまいます。<>#c7c7a8<><>180-196-179-150.aichiwest1.commufa.jp<>
1161<>1160<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月10日(火)  7:47<>管理人<><>お世話様です。<br><br>すいません、状況がよくわかりませんが通常はそのままエクスポートされると思います。<br><br>やったことはありませんが保存する時のオプションを開くとマッピングオプションで色々設定は出来るようなので試してみてはどうでしょうか。<>#c7c7a8<>MkfpKlB55Chbg<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1162<>1160<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月10日(火) 23:27<>sh<><>管理人様<br><br>ありがとうございました<>#c7c7a8<><>180-196-179-150.aichiwest1.commufa.jp<>
1167<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 14:21<>ゆうゆう<><>なぜPARTのとこにもアセンブリのところにも<br>３Ｄモデルのタグがあってスケッチなどがあるのですか？<br>アセンブリは作った部品を組んだりするだけではないのでしょうか？<>#c7c7a8<><>fw.daihen.co.jp<>
1169<>1167<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 14:52<>管理人<><>お世話様です。<br><br>アセンブリでもパーツをダブルクリックすると編集出来るようになってるのでスケッチがあります。<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1171<>1167<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 16:09<>ゆうゆう<><>ありがとうございます。<>#c7c7a8<><>fw.daihen.co.jp<>
1166<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 13:05<>色<>色の変更<>アプリケーションオプションでカラースキームをプレゼンテーションにして<br>背景を１色にしたのですが、また元にもどしたいのですが<br>最初の色の設定がわかりませんので教えてください。<>#c7c7a8<><>fw.daihen.co.jp<>
1168<>1166<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 14:50<>管理人<><>お世話様です。<br><br>最初の色はなんだったか覚えてませんが多分1色のミレニアムではないでしょうか？<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1170<><>jpg!:150!:105!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 15:21<>ＡＫ<>角度表示の仕方<>管理人様<br><br>いつもお世話になります。<br><br>添付図内のΦ23〜Φ14.18間の角度の表示の仕方のご相談です。<br>一般寸法を選択した後に、１つ目の線を選択します。その時にカーソルを線に線に寄せると、半円マークが出てきて、円の寸法記入になります。<br>どの様にすれば角度の表示になります。<br>宜しくお願いします。<>#c7c7a8<><>p80009-ipngn1302souka.saitama.ocn.ne.jp<>
1172<>1170<>jpg!:107!:150!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 16:23<>管理人<><>お世話様です。<br><br><br>「カーソルを線に線に寄せると、半円マークが出てきて、円の寸法記入になります。」<br><br>すいません、上記の状況がよくわかりませんが、画像のような角度線のことでしょうか？<br><br><br><>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1173<>1170<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 16:28<>ＡＫ<>角度表示の仕方<>管理人様<br><br>いつもお世話になります。<br><br>はい、画像の様な角度線を出したいです。<br>初歩的な質問ですみません。<br>宜しくお願いします。<>#c7c7a8<><>p80009-ipngn1302souka.saitama.ocn.ne.jp<>
1174<>1170<>png!:144!:150!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 16:56<>管理人<><>斜めの線を順番に選択すれば角度線が出るはずですが出ませんか？<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1175<>1170<>jpg!:150!:105!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 17:33<>ＡＫ<>角度表示の仕方<>管理人様<br><br>いつもお世話になります。<br><br>添付図の様なマークが出てきて、角度線が出ません。<br>宜しくお願いします。<>#c7c7a8<><>p80009-ipngn1302souka.saitama.ocn.ne.jp<>
1176<>1170<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月12日(木) 18:38<>管理人<><>すいません、理解しました。<br><br>断面部の2ミリの溝があると半円マークが出てきて、円の寸法記入が出るのを再現出来ました。<br>溝があるので実際には円弧になっている為ですね。<br><br>以下、やり方ですのでご参考にしてください。<br><br>１．ビューをクリックして選択状態にする<br>２．リボンのスケッチでスケッチを開始をクリック<br>３．斜め線の上をなぞるように線を書いてスケッチを終了<br>４．スケッチで書いた線を選択すると角度線が出ると思います<>#c7c7a8<>JJncNfGUmo1W.<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1177<>1170<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月13日(金)  9:14<>AK<>角度表示の仕方<>管理人様<br><br>いつもお世話になります。<br><br><br>ご指導有難うございます。<br>上記のやり方で記入できました。<br>また、ご相談させて頂きます。<>#c7c7a8<><>p80009-ipngn1302souka.saitama.ocn.ne.jp<>
1181<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月17日(火)  9:59<>hi<>外観ブラウザ　サムネイルについて<>管理人様<br>お世話になります。<br><br>新たに色を作成した際に、新色がサムネイル色に反映されないため、<br>他に設定項目があれば教えて下さい。<>#c7c7a8<><>113x34x63x90.ap113.ftth.ucom.ne.jp<>
1138<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月1日(日) 13:00<>山本<>三角リブの作図にて<>おせわになります。<br>折り曲げ薄板(t=1)にて、折り曲げブラケットの作図・3Dパーツにて<br>三角リブを、付けたく思います。<br>まず、3D化にて、思う平面にて、45°の角度にて、パーツを作成致しましたが、各平面に角度(45°)を、もって、三角の折り込み・プレスにて、曲げとリブ作成を、同時に加工と思います。<br>この三角の形状の作成方法を、教えて頂きたく思います。この三角の長さは4t、奥行きは2tになります。<br>たいていは、中央に配置に致したく思います。<br>よろしく、お願いいたします。<br><>#c7c7a8<><>zaq7a66af60.zaq.ne.jp<>
1150<>1138<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月3日(火)  7:55<>管理人<><>お世話様です。<br><br>すいませんが、ご質問のパーツの形状が把握出来ませんでした。<br>手書きのマンガでもいいので添付していただけないでしょうか。<>#c7c7a8<>01aW8yK7QeQzo<>pd2fa4f7a.miygnt01.ap.so-net.ne.jp<>
1151<>1138<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月3日(火)  8:15<>山本<>ご返事有難うございます。<>早速のご返事、有難うございます。<br>絵と言われましても、どの様に、表現したらよいのか、わかりませんので。<br>お手数を、お掛け致しますが。<br>「ミスミの技術講座・第125回　リブ加工」にて、記載されているものです。<br>「パーツ薄板折り曲げにて」、このリブをつけたく思います。<br>何卒、手順を、教えて頂きたく思います。<br>よろしくお願いいたします。<br><>#c7c7a8<><>zaq7a66af60.zaq.ne.jp<>
1153<>1138<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月3日(火) 12:26<>管理人<><>お世話様です。<br><br>色々とやってみましたが出来ませんでした。<br><br>念の為Autodeskに問い合わせてみましたが、非常に困難であるとの回答でした。<>#c7c7a8<>1TbIuPn9.8ibU<>pd2fa4f7a.miygnt01.ap.so-net.ne.jp<>
1154<>1138<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月3日(火) 12:33<>山本<>有難うございました。<>大変、お世話になりました。<br>色々と、無理を、お願いいたしました。<br>有難うございます。<br><>#c7c7a8<><>zaq7a66af60.zaq.ne.jp<>
1159<>1138<>png!:150!:119!:1!:png!:150!:119!:1!:!:!:!:!:!:!:!:!:<>2015年3月6日(金) 14:50<>INVENTORING<><>添付の形状でよければ可能です<br>曲げの軸に平行かつ曲げの２平面に中立な作業平面を作成<br>スケッチにて任意のリブ形状を書く<br>先にリブの凸側を押し出しにて結合→両側→すべて<br>次にリブの凹側を押し出しにて切り取り→両側→すべて<br>実際にリブを出した状態に近づける場合は<br>板厚を考慮したフィレット<>#b8a8c7<><>247.182.183.58.megaegg.ne.jp<>
1178<>1138<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月14日(土) 13:03<>山本<>３月６日のinventoring様へ<>正直、出来ないのがあり前でソンナモノとおもっていました。<br>この様な形状です。<br>ソリッドワークスの取説では、もう一つでした。<br>ソリッドエッジでは、上記にて、出来る(三角錐)みたいです。<br>本日、Fusion306を、使用することが出来ますとの、メールにて、Fusionの日本語の取説とうを、教えて貰いたく思いまして、サイトを見ましたら、そのものです。有難うございます。<br>モシ、何方か「Fusion360」の日本語取説を、ご存じでしたら、教えて頂きたく思います。<br>この方法です。<br>一度、練習致します。ありがとうございます。<br>言葉足らずにて、大変失礼いたしました。<>#c7c7a8<><>zaq7a66af60.zaq.ne.jp<>
1179<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月14日(土) 22:31<>sh<>スプラインの長さについて<>管理人様<br>お世話になります。<br><br>2D/3Dスケッチ内でスプラインの全長を拘束できるでしょうか？<>#c7c7a8<><>180-197-60-170.aichieast1.commufa.jp<>
1180<>1179<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月16日(月) 13:09<>管理人<><>お世話様です。<br><br>すみません、色々やってみましたがわかりませんでした。<>#c7c7a8<>ZHvCKh0opY5wE<>s210.ALPHA-w6.vectant.ne.jp<>
1182<>1179<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月17日(火) 23:23<>sh<><>管理人様<br><br>ありがとうございました。<>#c7c7a8<><>180-197-60-170.aichieast1.commufa.jp<>
1183<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月19日(木)  9:33<>ゆうゆう<><>４か所のフィレットを３か所に直したいとき、何を押せばフィレットしたくないとこを外せるのでしょうか？<>#c7c7a8<><>fw.daihen.co.jp<>
1184<>1183<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月19日(木) 14:35<>管理人<><>お世話様です。<br><br>コントロールキーを押しながら消したいところをクリックすれば出来ますのでお試しください。<>#c7c7a8<>1iftQMsD7wUo.<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1187<>1183<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月23日(月)  9:17<>ゆうゆう<><>ありがとうございます。<>#c7c7a8<><>fw.daihen.co.jp<>
1194<><>jpg!:150!:105!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月27日(金) 19:50<>ＡＫ<>作図方法<>管理人様　<br><br>いつもお世話になります。<br><br>添付図のテーパー部部の作図方法の伝授お願いします。<br>宜しくお願いします。<br><>#c7c7a8<><>p8159-ipngn1601souka.saitama.ocn.ne.jp<>
1199<>1194<>jpg!:150!:150!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月27日(金) 22:52<>管理人<><>お世話様です。<br><br>すみません、形状がよくわかりませんでした。<br>添付のような形状ではないですよね？<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1201<>1194<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月28日(土) 11:09<>ＡＫ<>Ｚピン作図方法<>管理人様　　<br><br>いつもお世話になります。<br><br>図面書き直しました。<br>宜しくお願いします。<br><>#c7c7a8<><>p8159-ipngn1601souka.saitama.ocn.ne.jp<>
1202<>1194<>jpg!:150!:105!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月28日(土) 11:10<>ＡＫ<>Ｚピン作図<>管理人様<br><br>いつもお世話になります。<br><br>添付忘れました。<br>宜しくお願いします。<>#c7c7a8<><>p8159-ipngn1601souka.saitama.ocn.ne.jp<>
1203<>1194<>jpg!:150!:116!:1!:jpg!:150!:83!:1!:jpg!:145!:150!:1!:!:!:!:!:<>2015年3月28日(土) 12:31<>管理人<><>お世話様です。<br><br>添付のような感じでしょうか。<br>YZ Planeなどでスケッチを作成し、対称に押し出せば出来ますのでお試しください。<br><>#c7c7a8<>fTI1mawZAVr9Y<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1204<>1194<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月28日(土) 12:34<>ＡＫ<>Ｚピン作図方法<>管理人様<br><br>いつもお世話になります。<br><br>作図できました。<br>有難うございました。<br>また、ご相談させて頂きます。<br>宜しくお願いします。<>#c7c7a8<><>p8159-ipngn1601souka.saitama.ocn.ne.jp<>
1193<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月26日(木) 22:07<>ななし<>図面尺度自動化について<>はじめまして、ilogicを使って図面を書く際に<br>表題欄に尺度を自動で入れたいのですが<br>ネットで見つけたプログラミングが、以下のもので<br>尺度が”1：1”のように入ります。<br>これをもしくは別のもので尺度が”１/１”に自動で入る場合のプログラミングに書き直したいのですが、<br>ご指導のほどよろしくお願いします。<br><br>”プログラミング”<br>Dim odrawdoc As DrawingDocument<br>odrawdoc = ThisApplication.ActiveDocument<br>customPropertySet = odrawdoc.PropertySets.Item(&quot;Inventor User Defined Properties&quot;)<br>For i = 1 To odrawdoc.Sheets.Count<br>' Make sure the desired property exists<br>Try<br> prop = customPropertySet.Item(&quot;Scale&quot; + Str(i))<br>Catch<br> ' Assume error means not found<br> customPropertySet.Add(&quot;&quot;, &quot;Scale&quot; + Str(i))<br>End Try<br>Try<br>iProperties.Value(&quot;Custom&quot;, &quot;Scale&quot; + Str(i)) = odrawdoc.sheets.item(i).DrawingViews.Item(1).ScaleString<br>Catch<br>End Try<br>Next i<br>InventorVb.DocumentUpdate()<>#c7c7a8<>JbmL8./WkTtfM<>softbank220056254013.bbtec.net<>
1198<>1193<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月27日(金) 22:44<>管理人<><>お世話様です。<br><br>すみませんがやり方がわかりません。<br><br>おそらくですが図面ビューダイアログボックスの尺度表示がそのまま表示されてるような気がしますので１/１には出来ないような気がします。<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1206<>1193<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月29日(日) 15:30<>ななし<><>管理人様　　<br><br>いつもお世話になります。<br><br>プログラミングの内容に尺度が１：１の時、Aに１/１を代入<br>尺度の表示には、Aを表示的なものにしたいのですが、<br>１：２、１：３の時もありますので、FOR文で何度かまわす的なやり方では<br>できないでしょうか？<br><br>初心者なものでよくわかっていませんが、ご指導よろしくお願いします。<>#c7c7a8<><>softbank220056254013.bbtec.net<>
1211<>1193<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 13:28<>管理人<><>表示を１／１にするには下記方法で出来るようですのでお試しください。<br><br>１．[スタイルおよび規格エディタ] の [一般]でプリセットの尺度を選択。<br>２．[新規作成]で１／２、１／３などを作成して保存。<br>３．必要に応じてテンプレートに保存<br>４．ビュー配置時に尺度で１／２、１／３などを選択。<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1212<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 13:37<>ＡＫ<>表示方法<>管理人様<br><br>いつもお世話になります。<br><br><br>先日は、お世話になりました。<br>つまらない質問ですが、<br>モデルでネジの作図をして、図面化した際に図面の方には、<br>ただの棒になってしまうのは必然ですか？それともモデルの様に<br>ネジとして図面することが出来ますか？<br>宜しくお願いします。<>#c7c7a8<><>p8159-ipngn1601souka.saitama.ocn.ne.jp<>
1213<>1212<>jpg!:150!:117!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 14:49<>管理人<><>お世話様です。<br><br>添付のような図にならないでしょうか？<>#c7c7a8<>Uco.1oBYhpy7s<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1215<>1212<>jpg!:150!:105!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 16:07<>ＡＫ<>表示方法<>管理人様<br><br>いつもお世話になります。<br><br><br>添付図の様になります。<>#c7c7a8<><>p8159-ipngn1601souka.saitama.ocn.ne.jp<>
1216<>1212<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 16:35<>管理人<><>図面ビューの表示オプションタブのねじフィーチャにチェックが入ってるでしょうか？<>#c7c7a8<>8pyxGv3q13REY<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1217<>1212<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 16:48<>ＡＫ<>表示方法<>管理人様<br><br>いつもお世話になります。<br><br><br>チェック無かったです。<br>すみませんでした。<br>また、ご相談させて頂きます。<>#c7c7a8<><>p8159-ipngn1601souka.saitama.ocn.ne.jp<>
1207<><>jpg!:150!:93!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月29日(日) 17:05<>sh<>図面へのスケッチ<>管理人様<br>お世話になります。<br><br>図面へのスケッチの仕方が分からないのでご教示お願いいたします。<br>添付のようにヒンジ中心からの円弧を描きたいのですが、スケッチモードに入ってもヒンジ中心にはスナップ吸着してくれません。<br>なにか設定があるのでしょうか？<br><br>よろしくお願いします。<>#c7c7a8<><>180-197-60-170.aichieast1.commufa.jp<>
1208<>1207<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月)  9:39<>管理人<><>お世話様です。<br><br>スケッチモード（ビューを選択後）でヒンジ中心を右クリックして「ジオメトリを投影」をクリックして再度お試しください。<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1209<>1207<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 10:53<>sh<><>ジオメトリを投影が薄い色で表示されていて選択できませんが、何か設定がありますでしょうか。<>#c7c7a8<><>113x34x158x125.ap113.ftth.ucom.ne.jp<>
1210<>1207<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月30日(月) 11:02<>管理人<><>ジオメトリを投影が薄い色で表示される状況が再現出来ませんでしたが、他の線も全て選択出来ないでしょうか？<br>もし、他の線が選択出来るならそこからヒンジ中心をスケッチすればいいと思います。<>#c7c7a8<><>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1218<>1207<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月31日(火)  0:29<>sh<><>管理人様<br><br>他の線も選択できません。<br>どこかチェックを入れれば直るものでしょうか。<>#c7c7a8<><>180-197-60-170.aichieast1.commufa.jp<>
1219<>1207<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月31日(火)  7:35<>管理人<><>ビューをクリックして選択してからスケッチを開始して、線が選択出来ないようでしたらその状況がこちらではわかりませんのですみませんが何とも言えませんね。<>#c7c7a8<>hNFemGDoMlv0o<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1220<>1207<>png!:150!:146!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月31日(火) 12:00<>INVENTORING<><>ビューを選択せずにスケッチに入るとジオメトリ投影は薄い灰色になります<br>必ずビューを選択してからスケッチに入ってください<>#b8a8c7<><>247.182.183.58.megaegg.ne.jp<>
1221<>1207<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月31日(火) 23:07<>sh<><>ビュー選択後のスケッチで解決しました。<br>ありがとうございました。<>#c7c7a8<><>180-197-60-170.aichieast1.commufa.jp<>
1190<><>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月25日(水) 17:12<>MACHINE<>製図背景色<>いつもお世話になっております。<br>製図の背景色を黒色にしたいのですが可能でしょうか？<br>よろしくお願いいたします。<>#c7c7a8<>hxqjXCyLzNA0Y<>f102-pc249.cty-net.ne.jp<>
1191<>1190<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月25日(水) 22:40<>管理人<><>お世話様です。<br><br>おそらく出来ないのではないでしょうか。<>#c7c7a8<>LYAmGUyhX6lzc<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1192<>1190<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年3月26日(木) 11:11<>MACHINE<><>そうですか有難う御座いました。<>#c7c7a8<>uznpPMqaFQ.qc<>f102-pc252.cty-net.ne.jp<>
1230<>1190<>png!:150!:130!:1!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年4月8日(水)  9:26<>jp.cadmama<><>図面環境で、ツール＞ドキュメントの設定＞シートタブ<br>右側の「色」で変更できます。<>#c7c7a8<>QkM1jwEU58RbM<>202.238.175.90<>
1231<>1190<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年4月8日(水)  9:30<>管理人<><>お世話様です。<br><br>なるほど、知らなかったです。<br>ありがとうございました。<>#c7c7a8<>2bNWvogEWnE4A<>pc6ad4e.miygnt01.ap.so-net.ne.jp<>
1232<>1190<>!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:!:<>2015年4月9日(木) 10:22<>MACHINE<><>いつも大変お世話になっております。<br>jp.cadmamaさん有難う御座いました。<br>勉強になりました。<>#c7c7a8<>dTYPva8m4YGPc<>f102-pc250.cty-net.ne.jp<>
